# Generated by Django 5.2.6 on 2026-02-16 09:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('viscosity', models.CharField(max_length=20)),
                ('oil_type', models.CharField(choices=[('Mineral', 'Mineral'), ('Synthetic', 'Synthetic'), ('Semi-Synthetic', 'Semi-Synthetic')], max_length=20)),
                ('api_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('jaso_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('change_interval_km', models.IntegerField(default=5000)),
                ('change_interval_months', models.IntegerField(default=6)),
                ('price_range', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike')], max_length=10)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('engine_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric')], max_length=10)),
                ('oil_capacity', models.FloatField(help_text='In liters')),
                ('recommended_oil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_for', to='oil_logic.oil')),
            ],
            options={
                'unique_together': {('brand', 'model', 'year', 'engine_type')},
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_oil_change_km', models.IntegerField()),
                ('last_oil_change_date', models.DateField(default=django.utils.timezone.now)),
                ('next_due_km', models.IntegerField(blank=True, null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oil_logic.vehicle')),
            ],
        ),
    ]
