# Generated by Django 5.2.6 on 2026-02-20 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oil_logic', '0004_cartitem_order_orderitem_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='puc_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VehicleRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('puc_expiry', models.DateField()),
                ('registration_date', models.DateField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oil_logic.vehicle')),
            ],
        ),
    ]
