# Generated by Django 5.2.6 on 2026-02-25 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oil_logic', '0008_vehicleregistration_owner_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleregistration',
            options={'verbose_name': 'Vehicle Registration', 'verbose_name_plural': 'Vehicle Registrations'},
        ),
    ]
