# Generated by Django 5.2.6 on 2026-03-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oil_logic', '0009_alter_vehicleregistration_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='driving_condition',
            field=models.CharField(choices=[('City', 'City/Traffic'), ('Highway', 'Highway/Long Drive'), ('Mixed', 'Mixed (Both)'), ('Off-road', 'Off-road/Rough terrain')], default='Mixed', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='mileage_range',
            field=models.CharField(choices=[('0-50k', '0-50,000 km'), ('50k-100k', '50,001-1,00,000 km'), ('100k-150k', '1,00,001-1,50,000 km'), ('Above-150k', 'Above 1,50,000 km')], default='0-50k', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='preferred_frequency',
            field=models.CharField(choices=[('3-4m', 'Every 3-4 months'), ('5-6m', 'Every 5-6 months'), ('12m', 'Every 12 months'), ('Manufacturer', 'As per manufacturer only')], default='5-6m', max_length=20),
        ),
    ]
