# Generated by Django 5.2.6 on 2026-03-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oil_logic', '0010_maintenance_driving_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oil',
            name='volume_liters',
            field=models.FloatField(default=1.0, help_text='Volume in Liters'),
        ),
    ]
