# Generated by Django 5.2.6 on 2026-03-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oil_logic', '0013_maintenance_current_km_servicerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='oil',
            name='vehicle_type',
            field=models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike'), ('Scooter', 'Scooter'), ('Truck', 'Truck')], default='Car', max_length=20),
        ),
    ]
