# Generated by Django 5.2.6 on 2026-03-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oil_logic', '0014_oil_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='oil',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='oils/'),
        ),
    ]
