# Generated by Django 5.2.6 on 2026-03-10 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oil_logic', '0016_oilvariant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OilVariant',
        ),
    ]
