# Generated by Django 5.2.6 on 2026-03-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oil_logic', '0018_oilvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='oilvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='oil_variants/'),
        ),
    ]
