# Generated by Django 5.2.6 on 2026-03-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oil_logic', '0020_oil_volume_1l_price_oil_volume_4l_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price per unit at time of purchase', max_digits=10),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='volume_liters',
            field=models.FloatField(default=1.0, help_text='Selected volume in liters'),
        ),
    ]
