# Generated by Django 5.2.6 on 2026-02-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oil_logic', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='oil',
            name='price_range',
        ),
        migrations.AddField(
            model_name='oil',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oil',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='oil',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='oil',
            name='rating',
            field=models.FloatField(default=4.5),
        ),
        migrations.AddField(
            model_name='oil',
            name='stock_count',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='variant_name',
            field=models.CharField(default='Standard', help_text='e.g. Vxi, Zxi, Turbo, ABS', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('brand', 'model', 'year', 'variant_name', 'engine_type')},
        ),
    ]
