# Generated by Django 5.2.6 on 2026-02-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oil_logic', '0002_alter_vehicle_unique_together_remove_oil_price_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='displacement_cc',
            field=models.IntegerField(default=0, help_text='Engine displacement in CC'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('CNG', 'CNG')], max_length=10),
        ),
    ]
