# Generated by Django 5.2.6 on 2026-02-24 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oil_logic', '0006_servicebooking_uservehicle'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uservehicle',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='uservehicle',
            name='user',
        ),
        migrations.DeleteModel(
            name='ServiceBooking',
        ),
        migrations.DeleteModel(
            name='UserVehicle',
        ),
    ]
