# Generated by Django 5.2.6 on 2026-02-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oil_logic', '0007_alter_uservehicle_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleregistration',
            name='owner_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
