# Generated by Django 5.2.6 on 2026-03-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oil_logic', '0011_oil_volume_liters'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='color',
            field=models.CharField(default='#3B82F6', help_text='Vehicle color in Hex (e.g. #FF0000)', max_length=7),
        ),
    ]
