# Generated by Django 5.2.6 on 2026-03-05 06:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oil_logic', '0012_maintenance_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='current_km',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('oil_type', models.CharField(max_length=100)),
                ('km', models.IntegerField()),
                ('service_center', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='oil_logic.maintenance')),
            ],
        ),
    ]
