# Generated by Django 6.0.3 on 2026-03-10 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oil_logic', '0015_oil_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OilVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_liters', models.FloatField(choices=[(1.0, '1L'), (4.0, '4L'), (5.0, '5L')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_count', models.IntegerField(default=100)),
                ('oil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='oil_logic.oil')),
            ],
            options={
                'unique_together': {('oil', 'volume_liters')},
            },
        ),
    ]
