# Generated by Django 5.2.6 on 2026-03-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oil_logic', '0019_oilvariant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='oil',
            name='volume_1L_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price for 1L', max_digits=10),
        ),
        migrations.AddField(
            model_name='oil',
            name='volume_4L_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Price for 4L', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='oil',
            name='volume_5L_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Price for 5L', max_digits=10, null=True),
        ),
    ]
