# Generated by Django 5.2.6 on 2026-03-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oil_logic', '0022_vehiclequery_recommendationfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tagline',
            field=models.CharField(blank=True, help_text='A short tagline to display on your profile.', max_length=255, null=True),
        ),
    ]
